[project]
name = "jacobian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=2.14.4",
    "jupyter>=1.1.1",
    "matplotlib>=3.9.3",
    "numpy>=2.1.3",
    "torch>=2.5.1",
    "transformer-lens>=2.9.1",
]
